version: '3.8'

services:
  php:
    build: ./
    ports:
       - ${PORT}:80
    expose:
       - 80
    networks:
       - php-sql
    restart:
      unless-stopped
    depends_on:
       - sql
    environment:
       - MYSQL_CONNECTION_URI=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sql:3306/${MYSQL_DATABASE}
  sql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    expose:
      - 3306
    volumes:
      - sql-data:/var/lib/mysql
    restart:
      unless-stopped
    networks:
      - php-sql
    logging:
      driver: none

volumes:
  sql-data:

networks:
  php-sql:
